//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\phmarques\Documents\GitHub\NCalc2\NCalc2\NCalc2.g4 by ANTLR 4.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591

namespace NCalc2.Grammar {

using System;
using System.Text;
using System.Globalization;
using System.Collections.Generic;
using NCalc2.Expressions;

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="NCalc2Parser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.3")]
[System.CLSCompliant(false)]
public interface INCalc2Visitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.orExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOrExpr([NotNull] NCalc2Parser.OrExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.multExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultExpr([NotNull] NCalc2Parser.MultExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.bitXorExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitXorExpr([NotNull] NCalc2Parser.BitXorExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.shiftExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitShiftExpr([NotNull] NCalc2Parser.ShiftExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.bitOrExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitOrExpr([NotNull] NCalc2Parser.BitOrExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.eqExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEqExpr([NotNull] NCalc2Parser.EqExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.unaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpr([NotNull] NCalc2Parser.UnaryExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.primaryExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpr([NotNull] NCalc2Parser.PrimaryExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.addExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddExpr([NotNull] NCalc2Parser.AddExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpr([NotNull] NCalc2Parser.ExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitId([NotNull] NCalc2Parser.IdContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.bitAndExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBitAndExpr([NotNull] NCalc2Parser.BitAndExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.relExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRelExpr([NotNull] NCalc2Parser.RelExprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue([NotNull] NCalc2Parser.ValueContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.ncalc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNcalc([NotNull] NCalc2Parser.NcalcContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="NCalc2Parser.andExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpr([NotNull] NCalc2Parser.AndExprContext context);
}
} // namespace NCalc2.Grammar
